### PR TITLE
Drop rbnacl-libsodium

### PR DESCRIPTION
**Pull request by Keruspe**
It's deprecated, we shouldn't be using it anymore.

It would be nice to get a release with this!

### CODE REVIEW

**Comment by Keruspe** [comment]
@petebrowne mind giving this a look?

**Comment by petebrowne** [comment]
Thanks for the PR!

**Comment by petebrowne** [comment]
@Keruspe would you consider this a major or minor version change?

**Comment by Keruspe** [comment]
I’m not sure. Wrt rbnacl it was a big change, but for macaroons it’s just an internal one...

I don’t think it’s worth a 2.0, but maybe a 1.1 ?

**Pull request merged**
